//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by cgfgoban.rc
//
#define IDS_FILTER_STRING               1
#define IDS_CUT                         2
#define IDS_COPY                        3
#define IDS_PASTE                       4
#define IDS_LOAD_FILTER                 5
#define IDS_SAVE_FILTER                 6
#define IDM_EXIT                        101
#define IDM_TEST                        102
#define IDM_ABOUT                       103
#define IDM_HELP                        104
#define ID_BAN_CLEAR                    105
#define ID_BAN_1                        107
#define ID_BAN_2                        108
#define ID_BAN_3                        109
#define ID_BAN_4                        110
#define ID_BAN_5                        111
#define ID_BAN_6                        112
#define ID_BAN_7                        113
#define ID_BAN_8                        114
#define IDB_BANMEN                      116
#define IDB_TOOLBAR                     117
#define IDM_CGF_VERSION                 1000
#define IDM_HOMEPAGE                    1001
#define IDM_HANDICAP                    1002
#define IDM_PRINT                       1003
#define IDM_COM_PORT                    1004
#define IDM_USE_SERIAL                  1005
#define IDM_KOMI                        1006
#define IDM_HUMAN_PLAY                  1008
#define IDM_PLACE_NAME                  1009
#define IDM_EVENT_NAME                  1010
#define IDM_ROUND_NAME                  1011
#define IDM_NNGS_NAME1                  1012
#define IDM_NNGS_NAME2                  1013
#define IDM_USE_SOCK                    1014
#define IDM_NNGS_MINUTES                1014
#define IDM_LONG_THINK                  1015
#define IDM_CONTINUOUS_PLAY             1016
#define IDM_AUTO_SAVE                   1017
#define IDM_USE_RANDOM                  1018
#define IDM_AITE_IP                     1019
#define IDM_NNGS_SERVER                 1020
#define IDM_USE_NNGS                    1021
#define IDM_GNUGO_ENGINE                1022
#define IDC_BLACK_TYPE                  1023
#define IDC_WHITE_TYPE                  1024
#define IDC_BLACK_NAME                  1025
#define IDC_WHITE_NAME                  1026
#define IDC_START_FIRST                 1027
#define IDC_START_TOTYU                 1028
#define IDC_BOARD_SIZE                  1030
#define IDM_GNUGO_DIRECTORY             1033
#define IDC_GNUGO_EX1                   1034
#define IDC_GNUGO_EX2                   1035
#define IDM_GNUGO_LIFEDEATH             1036
#define IDC_GNUGO_EX3                   1037
#define IDM_GTP_PATH                    1039
#define IDM_AI_RYUSEI                   1040
#define IDM_DEADSTONE                   40001
#define IDM_INIT_COMM                   40002
#define IDM_THINKING                    40003
#define IDM_PRINT_REN                   40004
#define IDM_SET_BOARD                   40005
#define IDM_HYOUKATI                    40006
#define IDM_SET_BAN19                   40007
#define IDM_SET_BAN13                   40008
#define IDM_SET_BAN9                    40009
#define IDM_TEXT_HYOUJI                 40010
#define IDM_PLAY_START                  40011
#define IDM_PASS                        40012
#define IDM_BAN_EDIT                    40013
#define IDM_BAN_CLEAR                   40014
#define IDM_KIFU_SAVE                   40015
#define IDM_FILE_WRITE                  40016
#define IDM_KIFU_OPEN                   40017
#define IDM_FROM_CLIPBOARD              40018
#define IDM_TOOLBAR                     40019
#define IDM_BACK1                       40020
#define IDM_FORTH1                      40021
#define IDM_BACK10                      40022
#define IDM_FORTH10                     40023
#define IDM_BACKFIRST                   40024
#define IDM_FORTHEND                    40025
#define IDM_PRINT_REN_NUMBER            40026
#define IDM_SEITEKI_KYOUKA              40027
#define IDM_SELF_PLAY                   40028
#define IDM_HANTEN                      40029
#define IDM_CLIPBOARD                   40030
#define IDM_PRINT_GUN                   40031
#define IDM_PRINT_KAKUTEI_JI            40032
#define IDM_EYE_TEST                    40033
#define IDM_BEFORE_DEAD_GUN             40034
#define IDM_SOUND                       40035
#define IDM_PRT_TO_CLIP                 40046
#define IDM_SGF_CLIPOUT                 40047
#define IDM_SETTING                     40048
#define IDM_GENE_MOVE1                  40050
#define IDM_GENE_MOVE2                  40051
#define IDM_PRT_HASH                    40052
#define IDM_PRT_ALL_HASH_MOVES          40053
#define IDM_BREAK                       40054
#define IDM_RESTART                     40055
#define IDM_UNDO                        40056
#define IDM_VIEW_FIGURE                 40057
#define IDM_VIEW_NUMBER                 40058
#define IDM_NEXT_TURN                   40059
#define IDM_NNGS_WAIT                   40060
#define IDM_SGMP_WAIT                   40061
#define IDM_CHINESE_RULE                40062
#define IDM_DLL_BREAK                   40063
#define IDM_VIEW_LIFEDEATH              40064
#define IDM_GNUGO_SETTING               40065
#define IDM_GNUGO_PLAY                  40066
#define IDM_RESIGN                      40067
#define IDM_ATVIEW                      40068
#define IDM_SHOW_CONSOLE                40070
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        110
#define _APS_NEXT_COMMAND_VALUE         40071
#define _APS_NEXT_CONTROL_VALUE         1041
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
